
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents",
  "version": "0.0.14",
  "versions": {
    "@openai/agents": "0.0.14",
    "openai": "^5.10.1"
  }
};

export default METADATA;
